export class CHWSWGForm{
    constructor(
        
	    public _id:string,
        public _rev:string,
        public Form:string,
        public DocReaders: string,
	    public TransDocAuthors: string,
        public txtTransAudit: string,
	    public rtOtherDoc: string,
        public nmOtherDoc_1: string,
        public nmOtherDoc: string,
        public rtOptionsInvoice: string,
        public nmOptionsInvoice_2_1   : string,
        public nmOptionsInvoice: string,
        public rtRecoveryDoc  : string,
        public nmCompgenOptionslist_2_1: string,
        public nmCompgenOptionslist  : string,
        public rtserverinvoices: string,
        public nmserverinvoices_2_1    : string,
        public nmserverinvoices: string,
        public rtTDASAR  : string,
        public nmTDASAR_2_1: string,
        public nmTDASAR_2  : string,
        public rtDistSB: string,
        public nmDistSB_2_1    :string,
        public nmDistSB_2:string,
        public rtXactionWS   :string,
        public nmactionWS_2_1:string,
        public nmactionWS_2    : string,
        public rtEmails: string,
        public nmEmails_2_1   : string,
        public nmEmails_2: string,
        public rtLicenseAgreements   : string,
        public rtLicenseAgreements_2_1: string,
        public rtLicenseAgreements_2   : string,
        public rtBVM: string,
        public nmBVM_2_1   : string,
        public nmBVM_2: string,
        public rtFtF: string,

        public DocCreatorCanon:string,
        public DocCreator:string,
        public OldForm: string,
        public DeletedBy: string,
        public DeletedOn: string,

        public nmFtF_2_1: string,
        public nmFtF_2: string,
        public rtProposal: string,
        public nmProposal_2_1: string,
        public nmProposal_2: string,
        public rtEUSurvey: string,
        public nmEUSurvey_2_1: string,
        public nmEUSurvey_2: string,
        public rtSoW: string,
        public nmSoW_2_1: string,
        public nmSoW_2: string,
        public rtConfig: string,
        public nmConfig_2_1: string,
        public nmConfig_2: string,
        public rtQuote: string,
        public nmQuote_2_1: string,
        public nmQuote_2: string,
        public rtPONumber: string,
        public nmPONumber_2_1: string,
        public nmPONumber_2: string,
        public rtLease: string,
        public nmLease_2_1: string,
        public nmLease_2: string,
        public rtDistInvoice: string,
        public nmDistInvoice_2_1: string,
        public nmDistInvoice_2: string,
        public rtIBMEUInvoice: string,
        public nmIBMEUInvoice_2_1: string,
        public nmIBMEUInvoice_2: string,
        public rtIBMSB: string,
        public nmIBMSB_2_1: string,
        public nmIBMSB_2: string,
        public rtXibminvoices: string,
        public nmibminvoices_2_1: string,
        public nmibminvoices_2: string,
        public rtXSRWorksheet: string,
        public nmSRWorksheet_2_1: string,
        public nmSRWorksheet_2: string,
        public txtEnduserTr: string,
        public txtTransactionNum: string,
        public txtRvwMethod: string,
        public txtRvwType: string,
        public txtChannel: string,
        public txtLogNo: string,
        public sigtimestamp: string,
        public signature: string,
        public txtStatus: string,
        public rbEuroUnionFlag: string,
        public dlgLogApprovers: string,
        public lock_status: string,
        public txtAssistAnalyst:string[],
        public txtLAName: string,
        public $REF:string,
        public dtACRBDate:string,
        public txtCPN:string,
        public txCountry:string,
        public txMajorMarket:string,
        public txGrowthMarket:string,
        public txGeo:string,
        public dtcreated: string,
        public dtmodified: string
    ){}
}