export class CHWForm{
    constructor(
        
	    public _id:string,
        public _rev:string,
        public Form:string,
        public txtLAName:string,
        public txtAssistAnalyst:string[],    
        public dlgLogApprovers:string,
        public txtStatus:string,
        public signature:string,
        public sigtimestamp: string,
	    public txtLogNo: string,
        public txtChannel: string,
        public txtRvwType: string,
        public lock_status:string,
        public txtRvwMethod: string,
        public txTransactionNum: string,
        public txEnduserTr: string,
        public txtCoverSheet   : string,
        public rtCoverSheet: string,
        public txtIBMInvoice  : string,
        public rtIBMInvoice: string,
        public txtIBMSpecial  : string,
        public rtIBMSpecial: string,
        public txtEUInvoice    : string,
        public rtEUInvoice: string,
        public txtUnbundling  : string,
        public rtUnbundling: string,
        public txtDistributor  : string,
        public rtDistributor: string,
        public txtLeaseDoc    :string,
        public rtLeaseDoc:string,
        public txtPO   :string,
        public rtPO:string,
        public txtSOWDoc    : string,
        public rtSOWDoc: string,
        public txtQuoteDoc   : string,
        public rtQuoteDoc: string,
        public txtF2F   : string,
        public rtF2F: string,
        public txtException   : string,
        public rtException: string,
        public txtOtherDocs   : string,
        public rtOtherDocs: string,
        public txtCHWAudit: string,
        public DocCreatorCanon:string,
        public DocCreator:string,
        public OldForm: string,
        public DeletedBy: string,
        public DeletedOn: string,
        public $REF:string,
        public dtACRBDate:string,
        public txtCPN:string,
        public isvalid:string,
        public txCountry:string,
        public txMajorMarket:string,
        public txGrowthMarket:string,
        public txGeo:string,
        public dtcreated: string,
        public dtmodified: string   
    ){}
}