export class CFMBGFForm {
    constructor(

        public _id: string,
        public _rev: string,
        public Form: string,
        public txtLAName: string,
        public txtAssistAnalyst: string[],
        public dlgLogApprovers: string,
        public txtStatus: string,
        public signature: string,
        public sigtimestamp: string,
        public txtLogNo: string,
        public txtChannel: string,
        public txtRvwType: string,
        public lock_status: string,
        public txtRvwMethod: string,
        public txTransactionNum: string,
        public txEnduserTr: string,
        public txtMktgEventType: string,
        public txtCoverSheet: string,
        public rtCoverSheet: string,
        public txtVendorVerifDoc: string,
        public rtVendorVerifDoc: string,
        public txtMktgVendorInvoice: string,
        public rtMktgVendorInvoice: string,
        public txtMktgPlan: string,
        public rtMktgPlan: string,
        public txtAttendeeList : string,
        public rtAttendeeList : string,
        public txtProofPay: string,
        public rtProofPay: string,
        public txtSalary: string,
        public rtSalary: string,
        public txtProofEmployment: string,
        public rtProofEmployment: string,
        public txtInelligible: string,
        public rtInelligible: string,
        public txtException: string,
        public rtException: string,
        public txtOtherDocs: string,
        public rtOtherDocs: string,
        public txtCFMBGFAudit: string,
        public DocCreatorCanon: string,
        public DocCreator: string,
        public OldForm: string,
        public DeletedBy: string,
        public DeletedOn: string,
        public $REF: string,
        public dtACRBDate: string,
        public txtCPN: string,
        public isvalid: string,
        public txCountry: string,
        public txMajorMarket: string,
        public txGrowthMarket: string,
        public txGeo: string,
        public dtcreated: string,
        public dtmodified: string
    ) { }
}