export class SwTransaction
{
    constructor(
        
	    public _id:string,
        public _rev:string,
        public Form:string,
        public txtLAName:string,
        public txtAssistAnalyst:string[],
        public  DocCreator:string,
        public dlgLogApprovers:string,
        public signature:string, 
        public txtStatus:string,
        public sigtimestamp:string,
        public txtLogNo:string,
        public txtChannel:string,
        public txtRvwType:string,
        public txtRvwMethod:string,
        public txTransactionNum:string,
        public txEnduserTr:string,
        public txtCoverSheet:string,
        public rtCoverSheet:string,
        public txtIBMSpecial:string,
        public rtIBMSpecial:string,
        public txtIBMInvoice:string,
        public rtIBMInvoice:string,
        public txtEUInvoice:string,
        public rtEUInvoice:string,
        public rtDistInvoice:string,
        public rtLeaseDoc:string,
        public rtPO:string,
        public rtQuoteDoc:string,
        public rtException:string,       
        public txtDistInvoice:string,
        public txtLeaseDoc:string,
        public txtPO:string,
        public lock_status:string,
        public txtQuoteDoc:string,
        public txtException:string,
        public txtOtherDocs:string,
        public rtOtherDocs:string,
        public txtSWAudit:string,
        public OldForm: string,
        public DeletedBy: string,
        public DeletedOn: string,
        public $REF:string,
        public dtACRBDate:string,
        public txtCPN:string,
        public isvalid:string,
        public txCountry:string,
        public txMajorMarket:string,
        public txGrowthMarket:string,
        public txGeo:string,
        public dtcreated: string,
        public dtmodified: string
    ){}
}